### ISSUE TITLE
Readthedocs shows an old version of the documentation

### ISSUE THREAD

**Issue by gbraad** [softwarefactory-project/DLRN#17]
According to the documentation you can do

```
$ pip install dlrn
```

however, there is no published package at https://pypi.python.org/pypi/DLRN.

Documentation at: http://dlrn.readthedocs.org/en/latest/ does not reflect the current version of `README.rst`. Currently it describes setting up a dev environment:

```
$ pip install --upgrade pip
$ pip install -r requirements.txt
$ python setup.py develop
```

**Comment by gbraad** [comment]
Trigger a build on RTFD ?

**Comment by apevec** [comment]
Re.  No published package at Pypi - we still haven't tagged 0.1 hence no release yet.
There are few reviews I'd like to see merged before pushing the tag,
https://review.rdoproject.org/r/#/c/930/ at least.

**Comment by javierpena** [comment]
Migrated to Taiga: https://tree.taiga.io/project/morucci-software-factory/us/3050
