### ISSUE TITLE
RFE provide stable DLRN interface for TripleO CI

### ISSUE THREAD

**Issue by sshnaidm** [softwarefactory-project/DLRN#22]
In TripleO CI we used delorean to build packages[1] from repositories with patches applied there. From 14-15 Jul this functionality was broken.
We need a possibility to build package from repository where checkouted to specific patch.[2]

[1] `./venv/bin/dlrn --config-file projects.ini --head-only --package-name $MAPPED_PROJ --local --build-env DELOREAN_DEV=1 --build-env http_proxy=${http_proxy:-} --info-repo rdoinfo"`
https://github.com/openstack-infra/tripleo-ci/blob/4eba02b2dee9344097fd92e9b5819b08746dc49c/scripts/tripleo.sh#L366
[2] Bug in launchpad for tracking on TripleO side: https://bugs.launchpad.net/tripleo/+bug/1604039

**Comment by apevec** [comment]
It is not a regression in DLRN tool, on July spec change on rpm-master THT was merged: https://review.rdoproject.org/r/1665 which works only with THT master source branch.
This worked before b/c rpm-master worked also with stable branches, after this change rpm-mitaka and rpm-liberty were created.

Workaround in tripleo-ci script has been proposed.

**Comment by apevec** [comment]
@sshnaidm @derekhiggins @slagle let's first collect requirements from the TripleO CI, here's my take:
* build packages on master and stable branches with non-merged changes in source branch
* packaging changes are not tested, distro git checkout is last merged on the corresponding branch as defined by rdoinfo metadata https://github.com/redhat-openstack/rdoinfo
* skip postinstall step during RPM build

Anything else? Is the list of packages which tripleo.sh  script can build limited to TripleO projects or any openstack project is supported?

**Comment by sshnaidm** [comment]
We use "sed"s also for making projects.ini file, could it be done by cli, templates, or any other options? It'd be great to have a comment near each option in projects.ini what is it for. Of course all this is lesser priority and could be postponed for now.

**Comment by derekhiggins** [comment]
We don't currently test packaging changes but we probably shouldn't restrict ourselves to that long term so I think the solution here should cover both source and packaging.

We're not just limited to the TripleO projects, we currently run tripleo ci on some non tripleo projects and hope to expand this as capacity allows.

We need to be able to run delorean multiple times on different projects and finish up with a repository that contains packages for all the projects it ran on iirc this is why we couldn't use --dev as it doesn't update the database.

The only other thing I think would be nice is a better way to retry if the error is a retryable one, we're currently looking at the DB for a RETRY status. Either a specific exit code or a --auto-retry arg could work.

**Comment by weshayutin** [comment]
also this work around has been propose. https://review.gerrithub.io/#/c/285176

**Comment by adarazs** [comment]
The problem might be that we were relying DLRN's old behavior, when it was doing something like `git checkout -b <branch> origin/<branch>` on the source without any way to prevent it. So we were overwriting the origin/<branch> refs to trick DLRN to check out what we needed to gate (and build).

According to @fredericlepied it works if we just place the change on top of the master branch, DLRN won't mess with it. I'm going to try to test this tomorrow and modify our CI and see if the changes stay there. We will also need to check if this works on stable branches.

This is the problematic part in our CI system that I will try changing: https://github.com/redhat-openstack/ansible-role-tripleo-gate/blob/master/tasks/dlrn-build.yml#L29-L38

**Comment by apevec** [comment]
Also needs to changed delorean_build in
https://github.com/openstack-infra/tripleo-ci/blob/master/scripts/tripleo.sh#L309

**Comment by fredericlepied** [comment]
Proposing this fix: http://review.rdoproject.org/r/1742

**Comment by apevec** [comment]
Looks like we have an issue in the initial repo setup, quoting @adarazs 

> currently --local does check out the distgit change if it's not there, so then it should actually check out the correct version (or fail that it's not there)

**Comment by adarazs** [comment]
I tried the change from @fredericlepied and it did leave the source repo though, so that's a step forward. But indeed, it checked out and left the distgit repo on `rpm-master` instead of switching to `rpm-mitaka` according to what was in projects.ini

**Comment by adarazs** [comment]
I made this fix for the rest of the issues: https://review.rdoproject.org/r/1754

**Comment by adarazs** [comment]
I think we can close this issue, both changes are merged and at least for Third party CI this is good enough. @sshnaidm, is there something else that needs to be address?

**Comment by sshnaidm** [comment]
@adarazs this issue is successfully solved, thank you and everybody who participated.
Although we have collected a few requirements above (in @derekhiggins message), I'd like to wait until all of them will be addressed in any way. For example "retry" option, etc.
Thanks

**Comment by sshnaidm** [comment]
@javierpena , hi

@derekhiggins will come back from pto next (or after next) week, I think it's worth to wait him anyway..
I think there is his requirement to run it multiple times:

> We need to be able to run delorean multiple times on different projects and finish up with a repository that contains packages for all the projects it ran on iirc this is why we couldn't use --dev as it doesn't update the database

From my side I'm curious if it's possible to pass parameters in projects.ini file in different way than running a lot of "sed"s on this file, while risking not to match current regexps.

**Comment by apevec** [comment]
proejcts.ini could be in-place edited using crudini(1) - available from RDO (and epel7) repos.

**Comment by sshnaidm** [comment]
there were good times
