### ISSUE TITLE
Migrate DLRN issues to Software Factory

### ISSUE THREAD

**Issue by apevec** [softwarefactory-project/DLRN#30]
Software Factory, aka SF ( https://softwarefactory-project.io/docs/ ) is a powerful platform to build software, combining Gerrit, Zuul, Nodepool, Jenkins and StoryBoard.
DLRN would add "trunk chasing" continuous packaging feature and first step in integrating it is to move the backlog to the SF's StoryBoard instance: https://softwarefactory-project.io/storyboard/#!/project_group/list

**Comment by apevec** [comment]
DLRN is now included in SF and SF issue tracker is now in Taiga https://tree.taiga.io/project/morucci-software-factory/issues
@javierpena would DLRN issues fit there with "DLRN" tag?

**Comment by javierpena** [comment]
Yes, that would be a good fit.

**Comment by javierpena** [comment]
We have been routinely using Taiga for a while now. Closing.
