### ISSUE TITLE
Add # patches_base magic comment to support rdopkg by default

### ISSUE THREAD

**Issue by yazug** [softwarefactory-project/DLRN#34]
It would be nice if when dlrn did builds it could add patches_base comment to the .spec after the Sources but before BuildArch

{noformat}
Source0: kuryr-lib-0.7.1.dev1-0.20171117165805.d8e39cd.tar.gz

# patches_base=d8e39cd

BuildArch: noarch

{noformat}

**Comment by javierpena** [comment]
Is this something we still want? I understand we are already doing it downstream, but I can't figure out if we need it in DLRN.

**Comment by apevec** [comment]
we don't
