### ISSUE TITLE
provide a prebuild container with a DLRN server

### ISSUE THREAD

**Issue by ssbarnea** [softwarefactory-project/DLRN#36]
For testing (or even deploying) dlrn instances it would be much more useful if we would have a container that we can run.

For example on tripleo-ci we want to test the promotion so we need a fake dlrn server to validate the process. If we would be able to just start a pre-build container any work for setting it up would no longer be needed (not to mention skipping the time for preparing it).

**Comment by javierpena** [comment]
I have migrated the issue as a new story in our Taiga board: https://tree.taiga.io/project/morucci-software-factory/us/2845
