### ISSUE TITLE
Delorean has to run with selinux enforced

### ISSUE THREAD

**Issue by strider** [softwarefactory-project/DLRN#7]
@trown has been working and testing a delorean policy on http://trunk-mgt.rdoproject.org. Would be interesting to get it running on delorean trunk instance.

Here is the selinux policy module: http://fpaste.org/223819/14321316/

The fpaste is of a `delorean.te` file.
This can be installed with:

```
# checkmodule -M -m -o delorean.mod delorean.te
# semodule_package -o delorean.pp -m delorean.mod
# semodule -i delorean.pp
```

Then adding a labeling rule for the data directory and relabeling the existing files:

```
# semanage fcontext -a -t httpd_sys_rw_content_t "/root/delorean/data(/.*)?"
# restorecon -Rv /root/delorean/data
```

**Comment by apevec** [comment]
Archiving pastebin content here:

    module delorean 1.0;

    require {
            type httpd_sys_rw_content_t;
            type svirt_lxc_net_t;
            type docker_t;
            class dir { setattr read create write getattr rmdir remove_name add_name };     
            class file { append execute setattr read create ioctl execute_no_trans write getattr link unlink open };
            class lnk_file { read unlink link setattr};
    }
    
    #============= docker_t ==============
    allow docker_t httpd_sys_rw_content_t:dir getattr;
    
    #============= svirt_lxc_net_t ==============
    allow svirt_lxc_net_t httpd_sys_rw_content_t:dir { write read create add_name remove_name rmdir setattr };
    allow svirt_lxc_net_t httpd_sys_rw_content_t:file { append write ioctl link read create open unlink setattr};
    allow svirt_lxc_net_t httpd_sys_rw_content_t:lnk_file { read unlink link setattr};

**Comment by derekhiggins** [comment]
Thanks, Was this on centos or fedora?
On F21 this is  working for me with no custom modules

sudo semanage fcontext -a -t svirt_sandbox_file_t "/tmp/delorean/data(/.*)?"
sudo semanage fcontext -a -t svirt_sandbox_file_t "/tmp/delorean/scripts(/.*)?"
mkdir /tmp/delorean/data
sudo restorecon -R /tmp/delorean

I'm not sure why I need to create the data directory before running restorecon, I would have thought it would get the correct context once semanage had been run.

**Comment by apevec** [comment]
@dmsimard
Does above selinux modules resolve all denials for you on F22 ?

**Comment by dmsimard** [comment]
It works with the module and the instructions provided by @strider but I had to adjust that last bit:

    # semanage fcontext -a -t httpd_sys_rw_content_t "/root/delorean/data(/.*)?"
    # restorecon -Rv /root/delorean/data

actually used:

    # semanage fcontext -a -t httpd_sys_rw_content_t "/root/delorean/data(/.*)?"
    # semanage fcontext -a -t httpd_sys_rw_content_t "/root/delorean/scripts(/.*)?"
    # restorecon -Rv /root/delorean

For the record, the AVC error with the permission denied was the following:

    type=AVC msg=audit(1441897500.157:754): avc:  denied  { read } for  pid=13754 comm="build_rpm_wrapp" name="build_rpm_wrapper.sh" dev="dm-1" ino=565190 scontext=system_u:system_r:svirt_lxc_net_t:s0:c53,c65 tcontext=unconfined_u:object_r:user_home_t:s0 tclass=file permissive=0

No permission denied errors so far (and package is building)

**Comment by apevec** [comment]
I tried docker_home_t on ./data/ but that doesn't help:

   avc:  denied  { write } for  pid=875 comm="build_rpm_wrapp" ... scontext=system_u:system_r:svirt_lxc_net_t:s0:c104,c397 tcontext=unconfined_u:object_r:docker_home_t:s0 tclass=dir permissive=0

**Comment by javierpena** [comment]
I think the switch to mock allowed DLRN to run with SELinux active. The current instance is running in Permissive, although from a quick check on the audit logs it looks like the issue is more related to having the user home directories running on NFS.

**Comment by javierpena** [comment]
This is already in Taiga: https://tree.taiga.io/project/morucci-software-factory/us/233 . In general terms, DLRN runs without any issue with SELinux set to Enforcing. Some details of the current production deployment need to be fixed, mostly related to the API and location of web-served files.
